version: '2'

services:
  bot:
    image: ghcr.io/mzrimsek/bastulos-bot:latest
    container_name: bastulos_bot
    environment:
      - TWITCH_CHANNEL_1=bastulos
      - OBS_URL=${OBS_URL}
      - OBS_PASSWORD=${OBS_PASSWORD}
      - TMI_TOKEN=${TMI_TOKEN}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID}
      - FIREBASE_CLIENT_CERT_URL=${FIREBASE_CLIENT_CERT_URL}
      - FIREBASE_DATABASE_URL=${FIREBASE_DATABASE_URL}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_BOT_USER_ID=${DISCORD_BOT_USER_ID}
    restart: unless-stopped