version: '3'

services:
  bot:
    image: ghcr.io/mzrimsek/bastulos-bot:latest
    container_name: bastulos_bot
    volumes:
      - /opt/bastulos-bot:/var/bot
    environment:
      - TWITCH_CHANNEL=${TWITCH_CHANNEL}
      - TWITCH_BOT_CLIENT_ID=${TWITCH_BOT_CLIENT_ID}
      - TWITCH_BOT_CLIENT_SECRET=${TWITCH_BOT_CLIENT_SECRET}
      - TWITCH_BOT_TOKENS_FILE_LOCATION=/var/bot/botTokens.json
      - TWITCH_CHANNEL_CLIENT_ID=${TWITCH_CHANNEL_CLIENT_ID}
      - TWITCH_CHANNEL_CLIENT_SECRET=${TWITCH_CHANNEL_CLIENT_SECRET}
      - TWITCH_CHANNEL_TOKENS_FILE_LOCATION=/var/bot/channelTokens.json
      - OBS_URL=${OBS_URL}
      - OBS_PASSWORD=${OBS_PASSWORD}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID}
      - FIREBASE_CLIENT_CERT_URL=${FIREBASE_CLIENT_CERT_URL}
      - FIREBASE_DATABASE_URL=${FIREBASE_DATABASE_URL}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_BOT_USER_ID=${DISCORD_BOT_USER_ID}
      - MQTT_BROKER_ADDRESS=${MQTT_BROKER_ADDRESS}
    restart: unless-stopped
